config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations'}
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :petlosts do
    collection do
      get :nearby
      get :loading_screen
      get :user_pets_losts
      get :download
      get :preview
      get :rescued_pets
    end
  end

  resources :petfounds do
    collection do
      get :user_pets_founds
    end
  end

  # , only: [:create, :new, :index, :destroy, :edit, :update, :show]
  # Defines the root path route ("/")
  # root "posts#index"
  get 'terms', to: 'pages#terms', as: :terms
  get 'privacy', to: 'pages#privacy', as: :privacy

  # Ruta para la vista detallada de la app Encuentra Mascotas
  get 'app_info', to: 'pages#app_info', as: :app_info
  resources :reviews, only: [:create]  # Solo habilitamos la acción 'create'

end

app/models/petlost.rb
class Petlost < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_many_attached :photos
  DOGBREEDS = [
    'Affenpinscher', 'Afghan Hound', 'Akita Americano', 'Akita Inu', 'Airedale Terrier',
    'Alaskan Malamute', 'American Eskimo Dog', 'American Foxhound',
    'American Staffordshire Terrier', 'American Water Spaniel', 'Anatolian Shepherd Dog',
    'Appenzeller Sennenhund', 'Azawakh', 'Basenji', 'Basset Hound', 'Beagle',
    'Beauceron', 'Bedlington Terrier', 'Bergamasco', 'Bernese Mountain Dog',
    'Bichón Frisé', 'Bluetick Coonhound', 'Bloodhound', 'Boerboel', 'Bolognese',
    'Border Collie', 'Border Terrier', 'Borzoi', 'Boston Terrier', 'Boxer',
    'Boykin Spaniel', 'Briard', 'Brussels Griffon', 'Bull Terrier', 'Bullmastiff',
    'Bulldog Americano', 'Bulldog Campeiro', 'Bulldog Francés', 'Bulldog Inglés',
    'Cairn Terrier', 'Cane Corso', 'Catahoula Leopard Dog', 'Cavalier King Charles Spaniel',
    'Central Asian Shepherd Dog', 'Chesapeake Bay Retriever', 'Chihuahua', 'Chin Japonés',
    'Chinook', 'Chinese Crested', 'Chow Chow', 'Clumber Spaniel', 'Cocker Spaniel',
    'Corgi', 'Coton de Tulear', 'Criollo', 'Curly-Coated Retriever', 'Dachshund (salchicha)',
    'Dálmata', 'Dandie Dinmont Terrier', 'Doberman Pinscher', 'Dogo Argentino',
    'Dogo de Burdeos', 'Entlebucher Mountain Dog', 'Estrela Mountain Dog',
    'English Coonhound', 'English Foxhound', 'English Setter', 'English Toy Spaniel',
    'English Toy Terrier', 'Eurasier', 'Field Spaniel', 'Fila Brasileño', 'Finnish Lapphund',
    'Finnish Spitz', 'Flat-Coated Retriever', 'Fox Terrier', 'Galgo Español',
    'Glen of Imaal Terrier', 'Golden Retriever',
    'Gordon Setter', 'Grand Basset Griffon Vendéen', 'Greater Swiss Mountain Dog',
    'Greyhound', 'Groenendael', 'Harrier', 'Havanese', 'Hokkaido', 'Husky de Alaska',
    'Icelandic Sheepdog', 'Irish Setter', 'Irish Terrier', 'Irish Water Spaniel',
    'Irish Wolfhound', 'Jack Russell Terrier', 'Japanese Chin', 'Kai', 'Kangal',
    'Kelpie Australiano', 'Keeshond', 'Kerry Blue Terrier', 'Kishu', 'Komondor',
    'Kuvasz', 'Lagotto Romagnolo', 'Leonberger', 'Lhasa Apso', 'Labrador Retriever',
    'Lakeland Terrier', 'Lowchen', 'Löwchen', 'Maltés', 'Manchester Terrier',
    'Maremma Sheepdog', 'Mastín Español', 'Mastín Napolitano', 'Miniature Pinscher',
    'Norfolk Terrier', 'Norwegian Elkhound', 'Norwegian Lundehund', 'Norwich Terrier',
    'Nova Scotia Duck Tolling Retriever', 'Otterhound', 'Papillon', 'Parson Russell Terrier',
    'Pastor Alemán', 'Pastor Australiano', 'Pastor Belga Malinois', 'Pastor Caucásico',
    'Pastor del Cáucaso', 'Pastor de Asia Central', 'Pastor de Shetland', 'Pekingese',
    'Petit Basset Griffon Vendéen', 'Phalène', 'Pharaoh Hound', 'Pitbull Terrier',
    'Plott', 'Pointer Inglés', 'Pomerania', 'Poodle', 'Presa Canario',
    'Perro Crestado Chino', 'Perro Lobo Checoslovaco', 'Perro Lobo de Saarloos',
    'Perro Lobo Italiano', 'Perro de Agua Americano', 'Perro de Agua Español',
    'Perro de Montaña de los Pirineos', 'Perro Sin Pelo', 'Pharaoh Hound',
    'Podenco Canario', 'Podenco Ibicenco', 'Portuguese Podengo', 'Portuguese Podengo Pequeno',
    'Portuguese Water Dog', 'Pug', 'Puli', 'Pyrenean Mastiff', 'Redbone Coonhound',
    'Rhodesian Ridgeback', 'Rottweiler', 'Russell Terrier', 'Samoyed', 'Samoyedo',
    'Schipperke', 'Schnauzer', 'Scottish Terrier', 'Sealyham Terrier', 'Setter Inglés',
    'Setter Irlandés', 'Shar Pei', 'Shiba Inu', 'Shih Tzu', 'Shikoku', 'Siberian Husky',
    'Silky Terrier', 'Skye Terrier', 'Smooth Fox Terrier', 'Spitz Alemán',
    'Staffordshire Bull Terrier', 'Sussex Spaniel', 'Swedish Vallhund', 'Terranova',
    'Tervueren', 'Thai Ridgeback', 'Tibetan Mastiff', 'Tibetan Spaniel', 'Tibetan Terrier',
    'Tosa Inu', 'Treeing Tennessee Brindle', 'Treeing Walker Coonhound', 'Vizsla',
    'Weimaraner', 'Welsh Corgi Cardigan', 'Welsh Corgi Pembroke', 'Welsh Springer Spaniel',
    'Welsh Terrier', 'West Highland White Terrier', 'Whippet', 'Wire Fox Terrier',
    'Xoloitzcuintli', 'Yorkshire Terrier'
  ]


  COLORS = ['bicolor', 'tricolor', 'otro color', 'negro', 'blanco', 'marrón', 'gris', 'canela', 'atigrado',
    'crema', 'dorado', 'leonado']

  CATBREEDS = ['abisinio', 'americano de pelo corto', 'angora', 'azul ruso', 'bengalí', 'bosque de noruega',
      'británico de pelo corto', 'burmés', 'chartreux', 'cornish rex', 'devon rex', 'egipcio', 'europeo', 'himalayo',
      'javanés', 'maine coon', 'mau egipcio', 'oriental', 'persa', 'ragdoll', 'siamés', 'siberiano', 'somalí', 'sphynx',
      'tonkinés', 'otros']

  validates :name, :color, :day_lost, presence: true
end

app/controllers/petlosts_controller.rb
class PetlostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :loading_screen, :nearby, :download,:preview,:rescued_pets]
  def new
    @petlost = Petlost.new
    authorize @petlost
  end

  def create
    @petlost = Petlost.new(petlost_params)
    authorize @petlost
    if @petlost.save
      redirect_to petlost_path(@petlost)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @petlost = Petlost.find(params[:id])
    authorize @petlost
  end

  def update
    @petlost = Petlost.find(params[:id])
    authorize @petlost
    if @petlost.update(petlost_params.except(:photos))
      if params[:petlost][:photos].present?
        params[:petlost][:photos].each do |photo|
          @petlost.photos.attach(photo)
        end
      end
    else
      @petlost.update(petlost_params.except(:photos))
    end
    redirect_to petlost_path(@petlost)
  end

  def index
    @petlosts = policy_scope(Petlost).where(finded: false) # Filtrar solo los que no han sido encontrados
    if params[:raza].present?
      @petlosts = @petlosts.where("breed ILIKE ?", "%#{params[:raza]}%")
    end
    if params[:color].present?
      @petlosts = @petlosts.where("color ILIKE ?", "%#{params[:color]}%")
    end
    if params[:signs].present?
      @petlosts = @petlosts.where("signs ILIKE ?", "%#{params[:signs]}%")
    end
    if params[:day_lost].present?
      @petlosts = @petlosts.where(day_lost: params[:day_lost])
    end

    if params[:type_pet].present?
      @petlosts = @petlosts.where("LOWER(type_pet) LIKE ?", "%#{params[:type_pet].downcase}%")
    end

    @petlosts = @petlosts.page(params[:page]).per(6)
  end


  def show
    @petlost = Petlost.find(params[:id])
    authorize @petlost
  end

  def destroy
    @petlost = Petlost.find(params[:id])
    authorize @petlost
    @petlost.destroy
    redirect_to petlosts_path, status: :see_other
  end

  def loading_screen
    authorize :petlost, :loading_screen?
  end

  def nearby
    authorize :petlost, :nearby?
    @petlosts = Petlost.geocoded
    respond_to do |format|
      format.html
    end
  end

  def user_pets_losts
    authorize :petlost, :user_pets_losts?
    @petlosts = Petlost.all
    @petlosts = current_user.petlost.page(params[:page]).per(6)
  end

  def download
    @petlost = Petlost.find(params[:format])
    authorize :petlost, :download?

    pdf = Prawn::Document.new

    page_width = pdf.bounds.width
    page_height = pdf.bounds.height

    background_image_url = "https://res.cloudinary.com/dqx97scli/image/upload/v1726694895/Flyer_empresa_de_energ%C3%ADa_renovable_moderno_profesional_verde_2_ampeaa.png"
    background_image_data = URI.open(background_image_url).read
    background_image = StringIO.new(background_image_data)

    pdf.image background_image, at: [0, page_height], width: page_width, height: page_height, position: :center

    pdf.bounding_box([0, page_height], width: page_width) do

      pdf.move_down 150
      large_image_width = page_width * 0.7
      small_image_width = (page_width * 0.9 - 30) / 2
      image_height = 250
      small_image_height = 250

      if @petlost.photos.count == 1
        large_photo = @petlost.photos.first
        large_photo_data = large_photo.download
        large_image = StringIO.new(large_photo_data)
        pdf.image large_image, width: large_image_width, height: image_height, position: :center
        pdf.move_down 10

     elsif @petlost.photos.count >= 2
        small_photos = @petlost.photos.limit(2)
        small_photos_width = small_image_width * small_photos.size + 20 * (small_photos.size - 1)
        start_x = (page_width - small_photos_width) / 2

        pdf.bounding_box([0, pdf.cursor], width: page_width, height: small_image_height) do
          small_photos.each_with_index do |photo, index|
            photo_data = photo.download
            small_image = StringIO.new(photo_data)
            x_position = start_x + index * (small_image_width + 20)
            pdf.image small_image, width: small_image_width, height: small_image_height, at: [x_position, pdf.cursor]
          end
        end
        pdf.move_down 10
      else
        pdf.text "No hay fotos disponibles.", align: :center
        pdf.move_down 10
      end


      pdf.text "Nombre: #{@petlost.name}", size: 24, style: :bold, align: :center
      pdf.move_down 10

      pdf.text "<b>Raza:</b> #{@petlost.breed}", size: 16, inline_format: true, align: :center
      pdf.text "<b>Color:</b> #{JSON.parse(@petlost.color).reject(&:blank?).join(", ")}", size: 16, inline_format: true, align: :center
      pdf.text "<b>Señales Distintivas:</b> #{@petlost.signs}", size: 16, inline_format: true, align: :center
      pdf.text "<b>Día en que se perdió:</b> #{@petlost.day_lost.strftime('%d de %B de %Y')}", size: 16, inline_format: true, align: :center
      pdf.text "<b>Dirección:</b> #{@petlost.address}", size: 16, inline_format: true, align: :center

      pdf.move_down 10
      pdf.text "Si tienes información sobre #{@petlost.name}, por favor contacta al siguiente número:", size: 16, style: :italic, align: :center
      pdf.text @petlost.user.phone_number, size: 18, style: :bold, align: :center
    end
    send_data(pdf.render,
    filename: "#{@petlost.name}-cartel-de-búsqueda.pdf",
      type: 'application/pdf')
  end


  def preview
    @petlost = Petlost.find(params[:format])
    authorize :petlost, :preview?

    pdf = Prawn::Document.new

    page_width = pdf.bounds.width
    page_height = pdf.bounds.height

    background_image_url = "https://res.cloudinary.com/dqx97scli/image/upload/v1726694895/Flyer_empresa_de_energ%C3%ADa_renovable_moderno_profesional_verde_2_ampeaa.png"
    background_image_data = URI.open(background_image_url).read
    background_image = StringIO.new(background_image_data)

    pdf.image background_image, at: [0, page_height], width: page_width, height: page_height, position: :center

    pdf.bounding_box([0, page_height], width: page_width) do

      pdf.move_down 150
      large_image_width = page_width * 0.7
      small_image_width = (page_width * 0.9 - 30) / 2
      image_height = 250
      small_image_height = 250

      if @petlost.photos.count == 1
        large_photo = @petlost.photos.first
        large_photo_data = large_photo.download
        large_image = StringIO.new(large_photo_data)
        pdf.image large_image, width: large_image_width, height: image_height, position: :center
        pdf.move_down 10

     elsif @petlost.photos.count >= 2
        small_photos = @petlost.photos.limit(2)
        small_photos_width = small_image_width * small_photos.size + 20 * (small_photos.size - 1)
        start_x = (page_width - small_photos_width) / 2

        pdf.bounding_box([0, pdf.cursor], width: page_width, height: small_image_height) do
          small_photos.each_with_index do |photo, index|
            photo_data = photo.download
            small_image = StringIO.new(photo_data)
            x_position = start_x + index * (small_image_width + 20)
            pdf.image small_image, width: small_image_width, height: small_image_height, at: [x_position, pdf.cursor]
          end
        end
        pdf.move_down 10
      else
        pdf.text "No hay fotos disponibles.", align: :center
        pdf.move_down 10
      end


      pdf.text "Nombre: #{@petlost.name}", size: 24, style: :bold, align: :center
      pdf.move_down 10

      pdf.text "<b>Raza:</b> #{@petlost.breed}", size: 16, inline_format: true, align: :center
      pdf.text "<b>Color:</b> #{JSON.parse(@petlost.color).reject(&:blank?).join(", ")}", size: 16, inline_format: true, align: :center
      pdf.text "<b>Señales Distintivas:</b> #{@petlost.signs}", size: 16, inline_format: true, align: :center
      pdf.text "<b>Día en que se perdió:</b> #{@petlost.day_lost.strftime('%d de %B de %Y')}", size: 16, inline_format: true, align: :center
      pdf.text "<b>Dirección:</b> #{@petlost.address}", size: 16, inline_format: true, align: :center

      pdf.move_down 10
      pdf.text "Si tienes información sobre #{@petlost.name}, por favor contacta al siguiente número:", size: 16, style: :italic, align: :center
      pdf.text @petlost.user.phone_number, size: 18, style: :bold, align: :center
    end
    send_data(pdf.render,
      filename: "#{@petlost.name}-cartel-de-búsqueda.pdf",
      type: 'application/pdf',
      disposition: 'inline')
  end


  def rescued_pets
    @petlosts = policy_scope(Petlost).where(finded: true).page(params[:page]).per(6) # Solo los que han sido rescatados
    authorize :petlost, :rescued_pets? # Asegúrate de autorizar la acción si usas Pundit
  end

  private

  def petlost_params
    params.require(:petlost).permit(:name, :gender, :type_pet, :breed, :signs, :day_lost, :address, :user_id, :finded, photos: [], color: [])
  end
end

app/views/petlosts/_form.html.erb
<%= stylesheet_link_tag 'pet/form', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= simple_form_for(petlost, html: { data: { controller: "alert", action: "submit->alert#showAlert", mode: petlost.new_record? ? "new" : "edit" } }) do |f| %>

  <div class="container-large">
    <div class="set">
      <div class="container-option">
        <%= f.input :name, label: "Nombre", placeholder: "Escribe el nombre aquí"%>
      </div>
      <div class="container-option">
        <p class="form-label">Género</p>
        <div class="radio-container customed-radio-group">
           <%= f.input :gender, as: :radio_buttons, collection:['Hembra', 'Macho'], item_label_class: 'label-modif' %>
        </div>
      </div>
    </div>

    <div class = "set">
      <div class="container-option">
        <%= f.input :color, label: "Color", collection: Petlost::COLORS, hint: 'Selecciona su(s) color(es). Si tiene más de dos, selecciona primero bicolor/tricolor y luego sus colores!', input_html: {
          multiple: true, class: "customed-bg", data: {
            controller: "tom-select",
            tom_select_options_value: { tags: true }
            }
          } %>
      </div>

      <div class="container-option">
        <div data-controller= 'type-pet'>
          <%# <label for="petlost_type_pet">Tipo de animal</label> %>
          <div class="pb-2">
            <p class="form-label">Tipo de animal</p>

            <div class="radio-container customed-radio-group">
              <%= f.input :type_pet, as: :radio_buttons, collection: ['Perro', 'Gato', 'Otro'], label: false, legend: false, item_label_class: 'label-modif',
                        input_html: {
                          data: {
                            action: "change->type-pet#showBreed"
                            },
                          } %>
            </div>
          </div>

          <div class="container-type">
            <%# contenedor perros %>
            <div data-type-pet-target="perro" class="d-none">
              <%= f.input :breed, label: false, collection: Petfound::DOGBREEDS, prompt: 'Selecciona su raza' %>
            </div>
            <%# contenedor gatos %>
            <div data-type-pet-target="gato" class="d-none">
              <%= f.input :breed, label: false, collection: Petfound::CATBREEDS, prompt: 'Selecciona su raza' %>
            </div>
            <%# contenedor otros %>
            <div data-type-pet-target="otro" class="d-none">
              <%= f.input :breed, label: false, placeholder: 'Escribe el tipo de animalito' %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <%= f.input :signs, label: 'Características/peculiaridades', placeholder: "Una buena descripción hará más fácil identificarlo!"%>

    <div class="set">
      <div class="container-option">
        <%= f.input :day_lost, label:'¿Cuándo se perdió?', placeholder: 'Selecciona una fecha',
                as: :string,
                input_html: {
                  data: {
                    controller: "datepicker",
                    datepicker_today_value: Date.today
                  }
                } %>
      </div>

      <div class="container-option">
        <%= f.input :photos, as: :file, label: 'Adjunta una foto o más fotos', input_html: { multiple: true } %>
        <% if @petlost.photos.attached? %>
          <p class= "form-label">Imágenes actuales:</p>
          <div class="current-photo d-flex flex-wrap justify-content-evenly">
          <% @petlost.photos.each do |photo| %>
            <div style="width: 80px; height: 80px; overflow: hidden;">
              <%= cl_image_tag photo.key, style: "width: 100%; height: 100%;" %>
            </div>
          <% end %>
          </div>
        <% end %>
      </div>

    </div>
    <%= f.input :address, label: "Ingresa la dirección donde se perdió", placeholder: 'Escribe la dirección completa'%>
    <%= f.hidden_field :user_id, value:current_user.id %>
    <%= f.hidden_field :finded, value: false %>
  </div>

  <div class="custom-buttoms-form">
    <%# <button data-controller='alert' data-action="click->alert#showAlert">Click me</button> %>
    <%= link_to "Regresar", petlosts_path, id: "back-home", class:"button-customed" %>
    <%= f.submit "Enviar", id: "submit-form", class:"button-customed"%>
  </div>
<% end %>

app/views/petlosts/_info_window.html.erb
<div>
  <h5><%= petlost.name %></h5>
  <p>Raza: <%= petlost.breed %></p>
  <p>Color: <%= petlost.color %></p>
  <p>Perdido el: <%= petlost.day_lost %></p>
</div>

app/views/petlosts/index.html.erb
<div class="fondo-azul-section">
  <div class="container mt-5">
    <div class="d-flex justify-content-between mb-4">
      <div>
        <%= link_to root_path, class: "btn btn-primary btn-lg text-white d-flex align-items-center justify-content-center" do %>
          <%= image_tag 'icons8-home.png', alt: 'Volver', width: 32, height: 32, class: 'me-2'  %> Volver
        <% end %>
      </div>
      <div>
        <%= link_to loading_screen_petlosts_path, class: 'btn btn-primary text-white' do %>
          <i class="fa-solid fa-paw"></i>
          <i class="fa-solid fa-location-dot me-2"></i>
          Mascotas cerca
        <% end %>
        <%= link_to new_petlost_path, class: 'btn btn-primary text-white ms-2' do %>
          <i class="fa-solid fa-dog me-2"></i>
          Perdi mi mascota
        <% end %>
      </div>
    </div>

    <div class="row">
      <!-- Columna para el filtro -->
      <div class="col-md-3">
        <div class="card" style="max-height: 400px; overflow-y: auto;">
          <div class="card-header">
            Filtro por búsqueda
          </div>
          <div class="card-body">
            <%= form_with url: petlosts_path, method: :get, local: true do %>

              <div class="form-group mb-2">
                <%= label_tag :raza, "Raza" %>
                <%= text_field_tag :raza, params[:raza], class: 'form-control' %>
              </div>

              <div class="form-group mb-2">
                <%= label_tag :color, "Color" %>
                <%= text_field_tag :color, params[:color], class: 'form-control' %>
              </div>

              <div class="form-group mb-2">
                <%= label_tag :señas, "Señas particulares" %>
                <%= text_field_tag :signs, params[:signs], class: 'form-control' %>
              </div>

              <div class="form-group mb-2">
                <%= label_tag :fecha_perdido, "Fecha perdido" %>
                <%= date_field_tag :day_lost, params[:day_lost], class: 'form-control' %>
              </div>

              <div class="form-group mb-2">
                  <%= label_tag :type_pet, "Tipo de mascota" %>
                  <%= text_field_tag :type_pet,params[:type_pet],class: 'form-control' %>
              </div>


              <%= button_tag(type: 'submit', class: 'btn btn-success btn-block text-white') do %>
                <i class="fa-solid fa-filter me-2"></i>
                Filtrar
              <% end %>

            <% end %>
          </div>
        </div>

        <!-- Video debajo del filtro -->
        <div class="mt-4">
          <video width="100%" height="auto" loop muted autoplay playsinline>
            <source src="<%= asset_path('videoejemplo.mp4') %>" type="video/mp4">
            Tu navegador no soporta la etiqueta de video.
          </video>
        </div>
      </div>

      <!-- Columna para las tarjetas -->
      <div class="col-md-9">
        <div class="row g-3">
          <% if @petlosts.any? %>
            <% @petlosts.each do |petlost| %>
              <div class="col-md-4">
                <div class="card mb-4 shadow-sm d-flex flex-column">
                  <% if petlost.photos.any? %>
                    <!-- Carrusel de fotos si hay más de una -->
                    <div id="carouselPetlost<%= petlost.id %>" class="carousel slide" data-bs-ride="carousel">
                      <div class="carousel-inner">
                        <% petlost.photos.each_with_index do |photo, index| %>
                          <div class="carousel-item <%= 'active' if index == 0 %>">
                            <%= cl_image_tag photo.key, class: 'd-block w-100 card-img-top pet-image', style: 'height: 200px; object-fit: cover;', alt: petlost.name %>
                          </div>
                        <% end %>
                      </div>
                      <!-- Controles del carrusel -->
                      <button class="carousel-control-prev" type="button" data-bs-target="#carouselPetlost<%= petlost.id %>" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Anterior</span>
                      </button>
                      <button class="carousel-control-next" type="button" data-bs-target="#carouselPetlost<%= petlost.id %>" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Siguiente</span>
                      </button>
                    </div>
                  <% else %>
                    <!-- Si no hay fotos, muestra una imagen predeterminada -->
                    <%= image_tag 'default-image.png', class: 'card-img-top', style: 'height: 200px; object-fit: cover;', alt: 'No image available' %>
                  <% end %>

                  <div class="card-body d-flex flex-column">
                    <h5 class="card-title mb-2"><%= petlost.name %></h5>

                    <div class="container-details d-flex justify-content-center mb-2">
                      <span class="m-0 badge" style="background-color: #f7c6c7; color:#000000; line-height: 1.5"><%= petlost.type_pet %></span>
                      <span class="m-0 badge" style="background-color: #0079c1; color:#FFFFFF; line-height: 1.5"><%= petlost.gender %></span>
                    </div>

                    <p class="card-text mb-1">
                      <span class="fw-bold" style="color: #00629D;">Perdido el:</span>
                      <span class="fw-normal text-dark"><%= petlost.day_lost.strftime("%d/%m/%Y") %></span>
                    </p>

                    <p class="card-text mb-1">
                      <span class="fw-bold" style="color: #00629D;">Raza:</span>
                      <span class="fw-normal text-dark"><%= petlost.breed %></span>
                    </p>

                    <% if petlost.color.present? %>
                      <% colors_array = JSON.parse(petlost.color).reject(&:blank?) %>
                      <p class="card-text mb-1">
                        <span class="fw-bold" style="color: #00629D;">Color:</span>
                        <span class="fw-normal text-dark"><%= colors_array.join(", ") %></span>
                      </p>
                    <% end %>

                    <p class="card-text mb-1">
                      <span class="fw-bold" style="color: #00629D;">Señas particulares:</span>
                      <span class="fw-normal text-dark"><%= petlost.signs %></span>
                    </p>

                    <p class="card-text mb-1">
                      <span class="fw-bold" style="color: #00629D;">Dirección donde se perdió:</span>
                      <span class="fw-normal text-dark"><%= petlost.address %></span>
                    </p>

                    <p class="card-text mb-1">
                    <span class="fw-bold" style="color: #00629D;">Tipo:</span>
                    <span class="fw-normal text-dark"><%= petlost.type_pet %></span>
                    </p>

                    <div class="mt-auto">
                      <%= link_to petlost_path(petlost), class: 'btn btn-success text-white mb-2' do %>
                        <i class="fa-solid fa-paw  me-2"></i>
                        Ver
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <p>No hay mascotas perdidas que coincidan con los filtros.</p>
          <% end %>
        </div>

        <!-- Paginación -->
        <div class="d-flex justify-content-center mt-4">
          <%= paginate @petlosts %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/petlosts/loading_screen.html.erb
<!-- Pantalla de carga -->
<div class="d-flex justify-content-center align-items-center vh-100 position-fixed top-0 start-0 w-100 h-100 bg-white" style="z-index: 9999;">
<iframe src='https://my.spline.design/encuentramascotascopy-f0c0cfbc6557c630e934e0e3dcfb3914/' frameborder='0' width='100%' height='100%'></iframe>
</div>

<script>
  // Redirige a la vista 'nearby' después de 7 segundos
  setTimeout(function() {
    window.location.href = "<%= nearby_petlosts_path %>";
  }, 10000);
</script>