config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations'}
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :petlosts do
    collection do
      get :nearby
      get :loading_screen
      get :user_pets_losts
      get :download
      get :preview
      get :rescued_pets
    end
  end

  resources :petfounds do
    collection do
      get :user_pets_founds
    end
  end

  # , only: [:create, :new, :index, :destroy, :edit, :update, :show]
  # Defines the root path route ("/")
  # root "posts#index"
  get 'terms', to: 'pages#terms', as: :terms
  get 'privacy', to: 'pages#privacy', as: :privacy

  # Ruta para la vista detallada de la app Encuentra Mascotas
  get 'app_info', to: 'pages#app_info', as: :app_info
  resources :reviews, only: [:create]  # Solo habilitamos la acción 'create'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="footer p-4">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-4 d-flex align-items-center">
        <!-- Logo -->
        <img src="<%= asset_path('https://res.cloudinary.com/dhfv2yrux/image/upload/v1726490745/logo-encuentramascotas-footer_rl0ked.png') %>" alt="Encuentra Mascotas" class="footer-logo me-3">
        <p>Conectamos mascotas perdidas con sus dueños a través de tecnología y comunidad.</p>
      </div>

      <div class="col-md-4 text-center">
        <h5>Enlaces útiles</h5>
        <ul class="list-unstyled">
          <li><i class="fa-solid fa-paw"></i> <%= link_to 'Mascotas Perdidas', petlosts_path %></li>
          <li><i class="fa-solid fa-paw"></i> <%= link_to 'Mascotas Encontradas', petfounds_path %></li>
          <li><i class="fa-solid fa-paw"></i> <%= link_to 'Términos y Condiciones', terms_path %></li>
          <li><i class="fa-solid fa-paw"></i> <%= link_to 'Política de Privacidad', privacy_path %></li>
        </ul>
      </div>

      <div class="col-md-4 text-center">
        <h5>Síguenos</h5>
        <ul class="list-unstyled social-icons">
          <li><a href="https://www.facebook.com"><i class="fab fa-facebook-f"></i> Facebook</a></li>
          <li><a href="https://www.instagram.com"><i class="fab fa-instagram"></i> Instagram</a></li>
          <li><a href="https://www.tiktok.com"><i class="fab fa-tiktok"></i> TikTok</a></li>
          <li><a href="https://chat.whatsapp.com/invite-code"><i class="fab fa-whatsapp"></i> WhatsApp</a></li>
        </ul>
      </div>
    </div>

    <!-- Línea de separación -->
    <div class="separator"></div>

<div class="text-center mt-4">
  <p>&copy; 2024 <%= link_to 'EncuentraMascotas', 'https://www.encuentramascotas.org', target: '_blank', class: 'footer-link' %> - Todos los derechos reservados</p>
</div>

  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dhfv2yrux/image/upload/v1726181623/logo-horizontal-encuentramascotas_tzezqv.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

<div class="d-flex">
    <%= link_to 'Zona rescatados', rescued_pets_petlosts_path, class: "navbar-brand", style:"color:#0079C2" %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%= link_to loading_screen_petlosts_path, class: 'btn btn-primary text-white me-3' do %>
            <i class="fa-solid fa-paw"></i>
            <i class="fa-solid fa-location-dot me-2"></i>
            Mascotas cerca
          <% end %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.photo.attached? %>
              <%= image_tag current_user.photo, class: "avatar", alt: "dropdown menu" %>
            <% else %>
              <%= image_tag "https://res.cloudinary.com/dqx97scli/image/upload/v1726180273/development/xcpqaf6zmnmygc31q6dp0rx7nd2m.png", class: "avatar", alt: "dropdown menu" %>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mi mascota", user_pets_losts_petlosts_path, class: "dropdown-item" %>
              <%= link_to "Mis Mascotas Encontradas", user_pets_founds_petfounds_path, class: "dropdown-item" %>
              <%= link_to "Editar perfil", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
</div>
  </div>
</div>