config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations'}
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :petlosts do
    collection do
      get :nearby
      get :loading_screen
      get :user_pets_losts
      get :download
      get :preview
      get :rescued_pets
    end
  end

  resources :petfounds do
    collection do
      get :user_pets_founds
    end
  end

  # , only: [:create, :new, :index, :destroy, :edit, :update, :show]
  # Defines the root path route ("/")
  # root "posts#index"
  get 'terms', to: 'pages#terms', as: :terms
  get 'privacy', to: 'pages#privacy', as: :privacy

  # Ruta para la vista detallada de la app Encuentra Mascotas
  get 'app_info', to: 'pages#app_info', as: :app_info
  resources :reviews, only: [:create]  # Solo habilitamos la acción 'create'

end

app/views/pages/app_info.html.erb
<div class="container mt-5">
  <h1 class="text-center">Descubre la App Encuentra Mascotas</h1>
  <p class="text-center">
    Nuestra aplicación está diseñada para conectar a las personas con sus mascotas perdidas mediante geolocalización en tiempo real, reportes inmediatos y una comunidad activa de amantes de los animales.
  </p>

  <div class="row align-items-center mt-5">
    <div class="col-md-6">
      <img src="<%= asset_path('https://res.cloudinary.com/dqx97scli/image/upload/v1726784735/app-encuentra-mascotas.png') %>" class="img-fluid app-image" alt="Encuentra Mascotas App en acción" style="max-height: 600px;">

    </div>
    <div class="col-md-6">
      <h2>Encuentra Mascotas: Conectando Mascotas con sus Dueños</h2>
      <p>
        Con nuestra tecnología avanzada y geolocalización en tiempo real, Encuentra Mascotas ofrece una solución rápida y efectiva para la búsqueda y reporte de mascotas perdidas.
      </p>
      <ul>
        <li>Geolocalización en tiempo real para ubicar mascotas.</li>
        <li>Reportes inmediatos de mascotas perdidas o encontradas.</li>
        <li>Búsqueda avanzada filtrada por raza, color y más.</li>
        <li>Interacción directa entre dueños y la comunidad.</li>
        <li>Sección especial de adopciones.</li>
      </ul>
      <p>
        Nuestra app es intuitiva, accesible y completamente gratuita, permitiendo a cualquier persona colaborar para encontrar mascotas perdidas y fomentar la adopción de animales.
      </p>
      <%= link_to 'Instala la App', '#', class: 'btn btn-primary btn-large custom-btn-found' %>
    </div>
  </div>

  <div class="row text-center mt-5">
    <div class="col-md-12">
      <h3>Beneficios Clave de Encuentra Mascotas</h3>
      <p>
        Usar Encuentra Mascotas te permite ahorrar tiempo en la búsqueda de tu mascota con la ayuda de geolocalización en tiempo real y notificaciones inmediatas. La plataforma facilita la interacción entre la comunidad, mejorando las posibilidades de encontrar a tu mascota rápidamente. Además, ofrece un entorno seguro para proteger tus datos, mientras fomenta una red solidaria y activa para la adopción y el rescate de mascotas.
      </p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!-- Carrusel que ocupa todo el ancho -->
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel" style="height: 500px;">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner" style="height: 500px;">
    <div class="carousel-item active">
      <img src="https://res.cloudinary.com/dhfv2yrux/image/upload/v1726180245/carrusel-encuentramascotas-2_fb_pifbom.png" class="d-block w-100" alt="Mascotas Felices" style="object-fit: cover; height: 100%; display: block;">
      <div class="carousel-caption d-md-block">
        <h5 class="animate__animated animate__fadeInLeft">Mascotas Felices</h5>
        <p class="animate__animated animate__fadeInUp">Encuentra y reúne a las mascotas perdidas con sus familias.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/dhfv2yrux/image/upload/v1726180244/carrusel-encuentramascotas-1_fb_hgwxek.png" class="d-block w-100" alt="Cuidado y Protección" style="object-fit: cover; height: 100%; display: block;">
      <div class="carousel-caption d-md-block">
        <h5 class="animate__animated animate__fadeInLeft">Cuidado y Protección</h5>
        <p class="animate__animated animate__fadeInUp">Protege a las mascotas de tu comunidad y comparte información importante.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/dhfv2yrux/image/upload/v1726180245/carrusel-encuentramascotas-3_fb_ceqvme.png" class="d-block w-100" alt="Adopta una Mascota" style="object-fit: cover; height: 100%; display: block;">
      <div class="carousel-caption d-md-block">
        <h5 class="animate__animated animate__fadeInLeft">Adopta una Mascota</h5>
        <p class="animate__animated animate__fadeInUp">Dale una segunda oportunidad a una mascota necesitada.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>



<!-- Botón Mascotas Perdidas -->
<div class="d-flex justify-content-center mb-5 ">
  <div class="mx-2">
    <!-- Botón Mascotas Perdidas -->
    <%= link_to 'Mascotas Perdidas', petlosts_path, class: 'btn btn-primary custom-btn-lost' %>
  </div>
  <div class="mx-2">
    <!-- Botón Mascotas Encontradas -->
    <%= link_to 'Mascotas Encontradas', petfounds_path, class: 'btn btn-primary custom-btn-found' %>
  </div>
</div>

<!-- Cards de Mascotas Perdidas -->
<div class="fondo-azul-section">
  <section class="container mt-5">
    <h2 class="text-center section-title" data-aos="fade-up">
      <i class="fa-solid fa-paw"></i> Mascotas Perdidas <i class="fa-solid fa-paw"></i>
    </h2>
    <div class="row g-3 mb-5"> <!-- Agregamos g-3 para espacio entre las tarjetas -->
      <% if @petlosts.present? %>
        <% @petlosts.each_with_index do |pet, index| %> <!-- Añadimos index para controlar el retraso -->

          <% if pet.color.present? %>
            <% colors_array = JSON.parse(pet.color).reject(&:blank?) %>
            <% if colors_array.size == 1 %>
              <% text = colors_array.join %>
            <% else %>
              <% text = colors_array.join(", ") %>
            <% end %>
          <% end %>

          <!-- Animación de cada tarjeta con retraso dinámico -->
          <div class="col-md-3" data-aos="fade-up" data-aos-delay="<%= index * 100 %>">
            <div class="card mb-4 shadow-sm">
              <% if pet.photos.attached? %>
                <%= image_tag pet.photos.first, class: 'card-img-top pet-image', alt: pet.name %>
              <% else %>
                <%= image_tag 'default-image.png', class: 'card-img-top pet-image', alt: 'No image available' %>
              <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= pet.name %></h5>
                <p class="card-text"><strong>Color: </strong><%= truncate(text, length: 100) %></p>
                <p><strong>Señas:</strong> <%= pet.signs %></p>
                <p><strong>Dirección:</strong> <%= pet.address %></p>

                <!-- Contenedor para alinear los botones -->
                <div class="d-flex justify-content-center align-items-center mt-2">
                  <%= link_to 'Ver más', petlost_path(pet), class: 'btn btn-success text-white' %>

                  <!-- Botón Compartir -->
<!-- Botón Compartir -->
<button class="btn btn-secondary share-button"
        data-title="¡Ayuda a encontrar a <%= pet.name %>!"
        data-text="Hola, soy <%= pet.name %>. Soy un <%= pet.breed %> de color <%= text %>. Me perdí el <%= pet.day_lost.strftime('%d/%m/%Y') %> en <%= pet.address %>. ¡Ayúdame a volver a casa!"
        data-url="<%= petlost_url(pet) %>"
        data-image-url="<%= pet.photos.attached? ? url_for(pet.photos.first) : '' %>">
  <i class="fa-solid fa-share-nodes"></i>
</button>

                </div>

              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>No hay mascotas perdidas disponibles.</p>
      <% end %>
    </div>
  </section>
</div>




<!-- Nueva Sección sobre la App Encuentra Mascotas -->
<div class="fondo-rosa-section">
  <section class="container app-info-section mt-5">
    <div class="row align-items-center">
      <div class="col-md-6" data-aos="fade-right"> <!-- Imagen animada -->
        <img src="<%= asset_path('https://res.cloudinary.com/dqx97scli/image/upload/v1726784735/app-encuentra-mascotas.png') %>" class="img-fluid app-image" alt="Encuentra Mascotas App">
      </div>
      <div class="col-md-6" data-aos="fade-left"> <!-- Texto animado -->
        <h2 class="section-title">Encuentra Mascotas: Conectando a las Mascotas Perdidas con sus Dueños</h2>
        <p class="section-text">
          Con nuestra tecnología avanzada y geolocalización en tiempo real, Encuentra Mascotas ofrece una solución rápida y efectiva para la búsqueda y el reporte de mascotas perdidas. Únete a nuestra comunidad para ayudar a reunir a las mascotas con sus dueños.
        </p>
        <ul class="section-features" data-aos="fade-up"> <!-- Animación en la lista -->
          <li>Geolocalización en tiempo real para ubicar mascotas perdidas.</li>
          <li>Registro rápido y fácil de mascotas perdidas y encontradas.</li>
          <li>Búsqueda avanzada por raza, color y características específicas.</li>
          <li>Comunicación directa entre usuarios para agilizar el proceso de reencuentro.</li>
          <li>Sección dedicada para mascotas en adopción.</li>
          <li>Alertas y notificaciones de avistamientos cercanos a tu ubicación.</li>
          <li>Acceso a una comunidad activa y comprometida en la protección de animales.</li>
        </ul>
        <p class="section-text" data-aos="fade-up" data-aos-delay="200">
          La aplicación es fácil de usar, permite el reporte inmediato de mascotas perdidas y encontradas, además de la búsqueda avanzada de mascotas en adopción. ¡Sé parte de la solución!
        </p>
        <%= link_to 'Ver más', app_info_path, class: 'btn btn-primary btn-large custom-btn-found', 'data-aos' => 'zoom-in' %>
      </div>
    </div>
  </section>
</div>



<!-- Cards de Mascotas Encontradas -->
<div class="fondo-azul-section">
  <section class="container mt-5">
    <h2 class="text-center section-title" data-aos="fade-up">
      <i class="fa-solid fa-paw"></i> Mascotas Encontradas <i class="fa-solid fa-paw"></i>
    </h2>
    <div class="row mb-5">
      <% if @petfounds.present? %> <!-- Evitar errores si no hay mascotas encontradas -->
        <% @petfounds.each_with_index do |pet, index| %> <!-- Añadimos index para el retraso dinámico -->

          <!-- Animación de cada tarjeta con retraso dinámico -->
          <div class="col-md-3" data-aos="fade-up" data-aos-delay="<%= index * 100 %>">
            <div class="card mb-4 shadow-sm">
              <% if pet.photos.attached? %>
                <%= image_tag pet.photos.first, class: 'card-img-top pet-image', alt: pet.breed %>
              <% else %>
                <%= image_tag 'default-image.png', class: 'card-img-top', alt: 'No image available' %>
              <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= pet.breed %></h5> <!-- Mostrando la raza del perro -->

                <% if pet.color.present? %>
                  <% colors_array = JSON.parse(pet.color).reject(&:blank?) %>
                  <% if colors_array.size == 1 %>
                    <% color_text = colors_array.join %>
                  <% else %>
                    <% color_text = colors_array.join(", ") %>
                  <% end %>
                <% else %>
                  <% color_text = "No especificado" %>
                <% end %>

                <p class="card-text"><strong>Color:</strong> <%= color_text %></p>
                <p><strong>Señas:</strong> <%= pet.signs %></p>
                <p><strong>Dirección:</strong> <%= pet.address %></p>
                <!-- Agregar link si es necesario -->
                <%= link_to 'Ver más', petfound_path(pet), class: 'btn btn-primary' %>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>No hay mascotas encontradas disponibles.</p> <!-- Mensaje alternativo si no hay datos -->
      <% end %>
    </div>

    <!-- Botón Mascotas Encontradas -->
    <div class="d-flex justify-content-center mb-5">
      <div class="mx-2" data-aos="fade-up">
        <%= link_to 'Mascotas Encontradas', petfounds_path, class: 'btn btn-primary custom-btn-found' %>
      </div>
    </div>
  </section>
</div>


<!-- Reviews de Usuarios -->
<div class="fondo-rosa-section">
  <section class="container mt-5">
    <h2 class="text-center section-title" data-aos="fade-up"><i class="fa-solid fa-paw"></i> Encontraron a sus mascotas <i class="fa-solid fa-paw"></i></h2>

    <turbo-frame id="reviews_frame">
      <div class="row">
        <% if @reviews.present? %> <!-- Evitar errores si no hay reseñas -->
          <% @reviews.each_with_index do |review, index| %> <!-- Añadimos index para retraso dinámico -->
            <div class="col-md-4" data-aos="fade-up" data-aos-delay="<%= index * 100 %>">
              <div class="card mb-4 shadow-sm">
                <div class="card-body text-center">
                  <!-- Mostrar la foto del usuario -->
                  <% if review.user.photo.attached? %>
                    <%= image_tag review.user.photo, class: "img-fluid rounded-circle mb-3", style: "width: 80px; height: 80px; object-fit: cover;" %>
                  <% else %>
                    <i class="fas fa-user-circle" style="font-size: 3rem; color: #0079c1;"></i>
                  <% end %>

                  <h5 class="card-title"><%= review.user.name %></h5> <!-- Mostrar el nombre del usuario -->
                  <p class="card-text"><%= review.content %></p> <!-- Mostrar la opinión -->

                  <!-- Mostrar las estrellas de la calificación -->
                  <div class="rating">
                    <% rating_value = review.rating || 0 %> <!-- Asignar 0 si el rating es nil -->
                    <% 5.times do |i| %>
                      <i class="fa fa-bone <%= 'text-warning' if i < rating_value %>"></i> <!-- Pintar estrellas -->
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <p>No hay reseñas disponibles.</p> <!-- Mensaje alternativo si no hay reseñas -->
        <% end %>
      </div>
    </turbo-frame>
  </section>
</div>

app/views/pages/privacy.html.erb
<h1 class="text-center mt-5">Política de Privacidad</h1>
<div class="container privacy-container mt-4">
  <p>
    En EncuentraMascotas, valoramos tu privacidad. Esta política de privacidad describe cómo recopilamos, usamos y protegemos tu información personal cuando accedes a nuestro sitio web.
  </p>

  <h3>1. Información que recopilamos</h3>
  <p>
    Podemos recopilar la siguiente información personal cuando utilizas nuestros servicios:
    <ul>
      <li>Nombre y detalles de contacto.</li>
      <li>Dirección de correo electrónico.</li>
      <li>Ubicación geográfica para el uso de la función de geolocalización.</li>
      <li>Información de la mascota que reportes como perdida o encontrada.</li>
    </ul>
  </p>

  <h3>2. Uso de la información</h3>
  <p>
    Utilizamos la información recopilada para los siguientes fines:
    <ul>
      <li>Conectar a dueños con sus mascotas perdidas.</li>
      <li>Enviar notificaciones en tiempo real sobre avistamientos de mascotas.</li>
      <li>Mejorar nuestros servicios y la experiencia del usuario.</li>
    </ul>
  </p>

  <h3>3. Protección de tus datos</h3>
  <p>
    Implementamos medidas de seguridad avanzadas para proteger tu información personal de accesos no autorizados, pérdida o alteración. Sin embargo, ninguna medida de seguridad es 100% segura, por lo que no podemos garantizar la protección absoluta.
  </p>

  <h3>4. Cookies</h3>
  <p>
    Nuestro sitio web utiliza cookies para mejorar la experiencia del usuario. Puedes optar por desactivar las cookies a través de la configuración de tu navegador, pero esto puede afectar algunas funcionalidades del sitio.
  </p>

  <h3>5. Cambios en la política de privacidad</h3>
  <p>
    Nos reservamos el derecho de actualizar esta política de privacidad en cualquier momento. Te notificaremos si se realizan cambios importantes.
  </p>

  <p class="mt-5">
    <%# Si tienes alguna pregunta sobre nuestra política de privacidad, por favor <%= link_to 'contáctanos', contact_path %>
  </p>
</div>

app/views/pages/terms.html.erb
<h1 class="text-center mt-5">Términos y Condiciones</h1>
<div class="container terms-container mt-4">
  <p>
    Bienvenido a EncuentraMascotas. Estos términos y condiciones describen las reglas y regulaciones para el uso del sitio web EncuentraMascotas.org.
  </p>

  <h3>1. Aceptación de los términos</h3>
  <p>
    Al acceder a este sitio web, asumimos que aceptas estos términos y condiciones. No continúes usando EncuentraMascotas si no estás de acuerdo con todos los términos y condiciones establecidos en esta página.
  </p>

  <h3>2. Licencia</h3>
  <p>
    A menos que se indique lo contrario, EncuentraMascotas y/o sus licenciantes poseen los derechos de propiedad intelectual de todo el material en EncuentraMascotas.org. Todos los derechos de propiedad intelectual están reservados.
  </p>

  <h3>3. Responsabilidad del Usuario</h3>
  <p>
    Como usuario, eres responsable de asegurarte de que la información que ingresas es precisa y veraz. EncuentraMascotas no se hace responsable de la información incorrecta proporcionada por los usuarios.
  </p>

  <h3>4. Política de Privacidad</h3>
  <p>
    Consulta nuestra <%= link_to 'Política de Privacidad', privacy_path %> para obtener más información sobre cómo manejamos tu información personal.
  </p>

  <h3>5. Modificaciones</h3>
  <p>
    EncuentraMascotas puede revisar estos términos y condiciones en cualquier momento. Si cambian, nos aseguraremos de notificar a los usuarios mediante una publicación en el sitio web.
  </p>

  <p class="mt-5">
    <%# Si tienes alguna pregunta sobre nuestros términos, no dudes en <%= link_to 'contactarnos', contact_path %>
  </p>
</div>