config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations'}
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :petlosts do
    collection do
      get :nearby
      get :loading_screen
      get :user_pets_losts
      get :download
      get :preview
      get :rescued_pets
    end
  end

  resources :petfounds do
    collection do
      get :user_pets_founds
    end
  end

  # , only: [:create, :new, :index, :destroy, :edit, :update, :show]
  # Defines the root path route ("/")
  # root "posts#index"
  get 'terms', to: 'pages#terms', as: :terms
  get 'privacy', to: 'pages#privacy', as: :privacy

  # Ruta para la vista detallada de la app Encuentra Mascotas
  get 'app_info', to: 'pages#app_info', as: :app_info
  resources :reviews, only: [:create]  # Solo habilitamos la acción 'create'

end

app/models/petfound.rb
class Petfound < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_many_attached :photos
  DOGBREEDS = [
    'Labrador Retriever', 'Golden Retriever', 'Pastor Alemán', 'Shih Tzu', 'Beagle',
    'Bulldog Inglés', 'Bulldog Francés', 'Rottweiler', 'Poodle', 'Chihuahua',
    'Dachshund', 'Boxer', 'Doberman Pinscher', 'Siberian Husky', 'Cocker Spaniel',
    'Pomerania', 'Yorkshire Terrier', 'Border Collie', 'Akita Inu', 'Shiba Inu',
    'Samoyedo', 'Corgi', 'Pitbull Terrier', 'Staffordshire Bull Terrier',
    'Boston Terrier', 'Cavalier King Charles Spaniel', 'Mastín Napolitano',
    'Mastín Español', 'Gran Danés', 'San Bernardo', 'Terranova', 'Bichón Frisé',
    'Maltés', 'Galgo Español', 'Greyhound', 'Dálmata', 'Airedale Terrier',
    'Fox Terrier', 'West Highland White Terrier', 'Setter Irlandés', 'Setter Inglés',
    'Pointer Inglés', 'Jack Russell Terrier', 'Bull Terrier', 'Shar Pei', 'Chow Chow',
    'Basenji', 'Lhasa Apso', 'Pug', 'Vizsla', 'Weimaraner', 'Basset Hound',
    'Bloodhound', 'Cane Corso', 'Presa Canario', 'Alaskan Malamute', 'Husky de Alaska',
    'Pastor Belga Malinois', 'Komondor', 'Kuvasz', 'Schipperke', 'Whippet', 'Saluki',
    'Afghan Hound', 'Irish Wolfhound', 'Scottish Terrier', 'Cairn Terrier',
    'Norfolk Terrier', 'Norwich Terrier', 'Skye Terrier', 'Sealyham Terrier',
    'Bullmastiff', 'Rhodesian Ridgeback', 'Spanish Water Dog', 'Portuguese Water Dog',
    'Lagotto Romagnolo', 'Perro de Montaña de los Pirineos', 'Perro de Agua Americano',
    'Perro de Agua Español', 'Perro Lobo Checoslovaco', 'Perro Lobo de Saarloos',
    'Briard', 'Beauceron', 'Pastor de Shetland', 'Pastor Australiano', 'Kelpie Australiano',
    'Dogo Argentino', 'Dogo de Burdeos', 'Leonberger', 'Fila Brasileño',
    'Pastor Caucásico', 'Pastor del Cáucaso', 'Pastor de Asia Central', 'Tosa Inu',
    'American Staffordshire Terrier', 'Perro Crestado Chino', 'Spitz Alemán',
    'Tervueren', 'Groenendael', 'Bergamasco', 'Perro Lobo Italiano', 'Kangal',
    'Chin Japonés', 'Hokkaido', 'Kai', 'Kishu', 'Shikoku', 'Thai Ridgeback',
    'Azawakh', 'Boerboel', 'Pharaoh Hound', 'Podenco Ibicenco', 'Podenco Canario',
    'Coton de Tulear', 'Barbet', 'Borzoi', 'Clumber Spaniel', 'Sussex Spaniel',
    'Field Spaniel', 'Welsh Springer Spaniel', 'Irish Water Spaniel', 'English Coonhound',
    'Bluetick Coonhound', 'Treeing Walker Coonhound', 'American Foxhound',
    'English Foxhound', 'Harrier', 'Petit Basset Griffon Vendéen', 'Grand Basset Griffon Vendéen',
    'Otterhound', 'Plott', 'Redbone Coonhound', 'Portuguese Podengo', 'Portuguese Podengo Pequeno',
    'Schipperke', 'Lowchen', 'Miniature Pinscher', 'Manchester Terrier', 'English Toy Terrier',
    'Australian Terrier', 'Silky Terrier', 'Australian Silky Terrier', 'Bedlington Terrier',
    'Border Terrier', 'Dandie Dinmont Terrier', 'Glen of Imaal Terrier', 'Irish Terrier',
    'Kerry Blue Terrier', 'Lakeland Terrier', 'Welsh Terrier', 'Wire Fox Terrier',
    'Smooth Fox Terrier', 'Russell Terrier', 'Parson Russell Terrier', 'Affenpinscher',
    'Brussels Griffon', 'Cavalier King Charles Spaniel', 'Papillon', 'Phalène',
    'English Toy Spaniel', 'Japanese Chin', 'Pekingese', 'Tibetan Spaniel',
    'Tibetan Terrier', 'Löwchen', 'Bolognese', 'Havanese', 'Italian Greyhound',
    'Chinese Crested', 'Xoloitzcuintli', 'Peruvian Inca Orchid', 'Swedish Vallhund',
    'Norwegian Lundehund', 'Finnish Lapphund', 'Icelandic Sheepdog', 'Entlebucher Mountain Dog',
    'Appenzeller Sennenhund', 'Greater Swiss Mountain Dog', 'Bernese Mountain Dog',
    'Finnish Spitz', 'Norwegian Elkhound', 'Swedish Elkhound', 'Keeshond', 'Eurasier',
    'American Eskimo Dog', 'Samoyed', 'Shikoku', 'Akita Americano', 'Central Asian Shepherd Dog',
    'Carpathian Shepherd Dog', 'Caucasian Shepherd Dog', 'Maremma Sheepdog', 'Estrela Mountain Dog',
    'Spanish Mastiff', 'Tibetan Mastiff', 'Anatolian Shepherd Dog', 'Komondor', 'Kuvasz',
    'Pyrenean Mastiff', 'Bulldog Americano', 'Bulldog Campeiro', 'Catahoula Leopard Dog',
    'Chinook', 'Redbone Coonhound', 'Treeing Tennessee Brindle', 'Boykin Spaniel',
    'Nova Scotia Duck Tolling Retriever', 'American Water Spaniel', 'Chesapeake Bay Retriever',
    'Curly-Coated Retriever', 'Flat-Coated Retriever', 'Irish Setter', 'Gordon Setter',
    'English Setter', 'Welsh Corgi Pembroke', 'Welsh Corgi Cardigan', 'Perro Sin Pelo', 'Otros', 'Criollo'
  ]

  COLORS = ['bicolor', 'tricolor', 'otro color', 'negro', 'blanco', 'marrón', 'gris', 'canela', 'atigrado',
    'crema', 'dorado', 'leonado']

  CATBREEDS = ['abisinio', 'americano de pelo corto', 'angora', 'azul ruso', 'bengalí', 'bosque de noruega',
      'británico de pelo corto', 'burmés', 'chartreux', 'cornish rex', 'devon rex', 'egipcio', 'europeo', 'himalayo',
      'javanés', 'maine coon', 'mau egipcio', 'oriental', 'persa', 'ragdoll', 'siamés', 'siberiano', 'somalí', 'sphynx',
      'tonkinés', 'otros']

  validates :color, :day_found, :color, presence: true

  # validates :address, length: { in: 5..20, message: "Direccion entre 5 y 20 caracteres" }

end

app/controllers/petfounds_controller.rb
class PetfoundsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @petfounds = policy_scope(Petfound)

    # Filtros
    if params[:raza].present?
      @petfounds = @petfounds.where("breed ILIKE ?", "%#{params[:raza]}%")
    end

    if params[:color].present?
      @petfounds = @petfounds.where("color ILIKE ?", "%#{params[:color]}%")
    end

    if params[:signs].present?
      @petfounds = @petfounds.where("signs ILIKE ?", "%#{params[:signs]}%")
    end

    if params[:day_found].present?
      @petfounds = @petfounds.where(day_found: params[:day_found])
    end

    if params[:type_pet].present?
      @petfounds = @petfounds.where("LOWER(type_pet) LIKE ?", "%#{params[:type_pet].downcase}%")
    end

    # Paginación
    @petfounds = @petfounds.page(params[:page]).per(6)
  end

  def show
    @petfound = Petfound.find(params[:id])
    authorize @petfound
    @marker = {
      lat: @petfound.latitude,
      lng: @petfound.longitude,
      info_window_html: render_to_string(partial: "info_window_found", locals: { petfound: @petfound })
    }
  end

  def destroy
    @petfound = Petfound.find(params[:id])
    authorize @petfound
    @petfound.destroy
    redirect_to petfounds_path, status: :see_other
  end

  def new
    @petfound = Petfound.new
    authorize @petfound
  end

  def create
    @petfound = Petfound.new(petfound_params)
    authorize @petfound
    if @petfound.save
      redirect_to petfound_path(@petfound)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @petfound = Petfound.find(params[:id])
    authorize @petfound
  end

  def update
    @petfound = Petfound.find(params[:id])
    authorize @petfound
    @petfound.update(petfound_params)
    redirect_to petfound_path(@petfound)
  end

  def user_pets_founds
    authorize :petfound, :user_pets_founds?
    @petfounds = Petfound.all
    @petfounds = current_user.petfound.page(params[:page]).per(6)
  end

  private

  def petfound_params
    params.require(:petfound).permit(:type_pet, :breed, :gender, :facts, :signs, :details, :day_found, :user_id, :address, photos: [], color: [])
  end
end

app/views/petfounds/_form.html.erb
<%= stylesheet_link_tag 'pet/form', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= simple_form_for(petfound, html: { data: { controller: "alert", action: "submit->alert#showAlert", mode: petfound.new_record? ? "new" : "edit" } }) do |f| %>

  <div class="container-large">
    <div class="set">
      <div class="container-option">
        <div data-controller= 'type-pet'>
          <div class="pb-3">
            <p class="form-label">Tipo de animal</p>

            <div class="radio-container customed-radio-group">
              <%= f.input :type_pet, as: :radio_buttons, collection: ['Perro', 'Gato', 'Otro'], legend: false, item_label_class: 'label-modif',
                        input_html: {
                          data: {
                            action: "change->type-pet#showBreed"
                            },
                          } %>
            </div>
          </div>

          <div class="container-type">
            <%# contenedor perros %>
            <div data-type-pet-target="perro" class="d-none">
              <%= f.input :breed, label: false, collection: Petfound::DOGBREEDS, prompt: 'Selecciona su raza' %>
            </div>
            <%# contenedor gatos %>
            <div data-type-pet-target="gato" class="d-none">
              <%= f.input :breed, label: false, collection: Petfound::CATBREEDS, prompt: 'Selecciona su raza' %>
            </div>
            <%# contenedor otros %>
            <div data-type-pet-target="otro" class="d-none">
              <%= f.input :breed, label: false, placeholder: 'Escribe el tipo de animalito' %>
            </div>
          </div>
        </div>
      </div>

      <div class="container-option">
        <p class="form-label">Género</p>
        <div class="radio-container customed-radio-group">
          <%= f.input :gender, as: :radio_buttons, collection:['Hembra', 'Macho'], item_label_class: 'label-modif' %>
        </div>
      </div>

    </div>

    <div class="set">

      <div class="container-option">
        <%= f.input :color, label: "Color", collection: Petfound::COLORS, hint: 'Selecciona su(s) color(es). Si tiene más de dos, selecciona primero bicolor/tricolor y luego sus colores!', input_html: {
          multiple: true, class: "customed-bg", data: {
            controller: "tom-select",
            tom_select_options_value: { tags: true }
            }
          } %>
      </div>

      <div class="container-option">
        <p class="form-label">¿Cuál es su estado actual?</p>
        <div class="radio-container">
          <%= f.input :facts, as: :radio_buttons, collection: ["Le estoy dando refugio", "Iba pasando por la zona y lo vi", "Otras circunstancias"], item_label_class: 'customed-radio-label'%>
        </div>
      </div>

    </div>

    <%= f.input :signs, label: 'Características/peculiaridades', placeholder: "Una buena descripción hará más fácil que lo identifiquen!" %>

    <div class="set">

      <div class="container-option">
        <%= f.input :day_found, label: '¿Cuándo lo encontraste?', placeholder: 'Selecciona una fecha',
              as: :string,
              input_html: {
                data: {
                  controller: "datepicker",
                  datepicker_today_value: Date.today
                }
              } %>
      </div>

      <div class="container-option">
        <%= f.input :photos, as: :file, label: 'Adjunta una foto o más fotos', input_html: { multiple: true } %>
        <% if @petfound.photos.attached? %>
          <p class= "form-label">Imágenes actuales:</p>
          <div class="current-photo d-flex flex-wrap justify-content-evenly">
          <% @petfound.photos.each do |photo| %>
            <div style="width: 80px; height: 80px; overflow: hidden;">
              <%= cl_image_tag photo.key, style: "width: 100%; height: 100%;" %>
            </div>
          <% end %>
          </div>
        <% end %>
      </div>

    </div>

    <%= f.input :details, label: 'Detalles adicionales', placeholder: "Cuéntanos un poco de la mascota encontrada. Todo detalle cuenta!" %>
    <%= f.input :address, label: "Ingresa la dirección donde se perdió", placeholder: 'Escribe la dirección completa'%>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>


  <div class="custom-buttoms-form">
    <%= link_to "Regresar", petfounds_path, id: "back-home", class:"button-customed" %>
    <%= f.submit "Enviar", id: "submit-form", class:"button-customed"%>
  </div>

<% end %>

app/views/petfounds/_info_window_found.html.erb
<div>
  <strong><%= petfound.details %></strong>
  <p>Raza: <%= petfound.breed %></p>
  <p>Color: <%= petfound.color %></p>
  <p>Encontrado el: <%= petfound.day_found %></p>
</div>

app/views/petfounds/edit.html.erb
<%= stylesheet_link_tag 'pet/form', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="body-form">
  <div class="signup-container">
    <div class="left-container">
    </div>

    <div class='right-container'>
      <div class="container-title">
      <h1 class="mb-3">Mascota encontrada</h1>

      <h5>Aquí puedes editar los datos de tu mascotita</h5>
      </div>
      <%= render "form", petfound: @petfound %>
    </div>
  </div>
</div>

app/views/petfounds/index.html.erb
<div class="fondo-rosa-section">
  <div class="container mt-5">
    <!-- Botones de navegación superior -->
    <div class="d-flex justify-content-between mb-4">
      <div>
        <%= link_to root_path, class: "btn btn-success btn-lg text-white d-flex align-items-center justify-content-center" do %>
          <%= image_tag 'icons8-home.png', alt: 'Volver', width: 32, height: 32, class: 'me-2'  %> Volver
        <% end %>
      </div>
      <div>
        <%= link_to new_petfound_path, class: 'btn btn-success text-white ms-2' do %>
          <i class="fa-solid fa-dog me-2"></i>
          Encontré una mascota
        <% end %>
      </div>
    </div>

    <div class="row">
      <!-- Columna para el filtro -->
      <div class="col-md-3">
        <div class="card" style="max-height: 400px; overflow-y: auto;">
          <div class="card-header">
            Filtro por búsqueda
          </div>
          <div class="card-body">
            <%= form_with url: petfounds_path, method: :get, local: true do %>
              <div class="form-group mb-2">
                <%= label_tag :raza, "Raza" %>
                <%= text_field_tag :raza, params[:raza], class: 'form-control' %>
              </div>

              <div class="form-group mb-2">
                <%= label_tag :color, "Color" %>
                <%= text_field_tag :color, params[:color], class: 'form-control' %>
              </div>

              <div class="form-group mb-2">
                <%= label_tag :señas, "Señas particulares" %>
                <%= text_field_tag :signs, params[:signs], class: 'form-control' %>
              </div>

              <div class="form-group mb-2">
                <%= label_tag :fecha_encontrado, "Fecha encontrado" %>
                <%= date_field_tag :day_found, params[:day_found], class: 'form-control' %>
              </div>

              <div class="form-group mb-2">
                  <%= label_tag :type_pet, "Tipo de mascota" %>
                  <%= text_field_tag :type_pet,params[:type_pet],class: 'form-control' %>
              </div>


              <%= button_tag(type: 'submit', class: 'btn btn-success btn-block text-white') do %>
                <i class="fa-solid fa-filter me-2"></i>
                Filtrar
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

      <!-- Columna para las tarjetas -->
      <div class="col-md-9">
        <div class="row g-3">
          <% if @petfounds.any? %>
            <% @petfounds.each do |petfound| %>
              <div class="col-md-4">
                <div class="card mb-4 shadow-sm d-flex flex-column">
                  <!-- Carrusel de fotos -->
                  <% if petfound.photos.any? %>
                    <div id="carouselPetfound<%= petfound.id %>" class="carousel slide" data-bs-ride="carousel">
                      <div class="carousel-inner">
                        <% petfound.photos.each_with_index do |photo, index| %>
                          <div class="carousel-item <%= 'active' if index == 0 %>">
                            <%= cl_image_tag photo.key, class: 'd-block w-100 pet-image', style: 'height: 200px; object-fit: cover;', alt: petfound.details %>
                          </div>
                        <% end %>
                      </div>
                      <!-- Controles del carrusel -->
                      <button class="carousel-control-prev" type="button" data-bs-target="#carouselPetfound<%= petfound.id %>" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Anterior</span>
                      </button>
                      <button class="carousel-control-next" type="button" data-bs-target="#carouselPetfound<%= petfound.id %>" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Siguiente</span>
                      </button>
                    </div>
                  <% else %>
                    <!-- Si no hay fotos, muestra una imagen predeterminada -->
                    <%= image_tag 'default-image.png', class: 'card-img-top', style: 'height: 200px; object-fit: cover;', alt: 'No image available' %>
                  <% end %>

                  <div class="card-body d-flex flex-column">
                    <h5 class="card-title mb-2"><%= petfound.details %></h5>

                    <div class="container-details d-flex justify-content-center mb-2">
                      <span class="m-0 badge" style="background-color: #f7c6c7; color:#000000; line-height: 1.5"><%= petfound.type_pet %></span>
                      <span class="m-0 badge" style="background-color: #0079c1; color:#FFFFFF; line-height: 1.5"><%= petfound.gender %></span>
                    </div>
                    <p class="card-text mb-1">
                      <span class="fw-bold" style="color: #00629D;">Reporte:</span>
                      <% if petfound.facts=="Le estoy dando refugio" %>
                        <span class="fw-normal text-dark"><%= petfound.facts %> desde el <%= petfound.day_found.strftime("%d/%m/%Y") %></span>
                      <% elsif petfound.facts=="Iba pasando por la zona y lo vi" %>
                        <span class="fw-normal text-dark"><%= petfound.facts %> el <%= petfound.day_found.strftime("%d/%m/%Y") %></span>
                      <% elsif petfound.facts=="Otras circunstancias" %>
                        <span class="fw-normal text-dark"><%= petfound.facts %> - Fecha: <%= petfound.day_found.strftime("%d/%m/%Y") %></span>
                      <% end %>
                    </p>

                    <p class="card-text mb-1">
                      <span class="fw-bold" style="color: #00629D;">Raza:</span>
                      <span class="fw-normal text-dark"><%= petfound.breed %></span>
                    </p>

                    <% if petfound.color.present? %>
                      <% colors_array = JSON.parse(petfound.color).reject(&:blank?) %>
                      <p class="card-text mb-1">
                        <span class="fw-bold" style="color: #00629D;">Color:</span>
                        <span class="fw-normal text-dark"><%= colors_array.join(", ") %></span>
                      </p>
                    <% end %>

                    <p class="card-text mb-1">
                      <span class="fw-bold" style="color: #00629D;">Señas particulares:</span>
                      <span class="fw-normal text-dark"><%= petfound.signs %></span>
                    </p>

                    <p class="card-text mb-1">
                      <span class="fw-bold" style="color: #00629D;">Dirección donde fue encontrado:</span>
                      <span class="fw-normal text-dark"><%= petfound.address %></span>
                    </p>

                    <p class="card-text mb-1">
                    <span class="fw-bold" style="color: #00629D;">Tipo:</span>
                    <span class="fw-normal text-dark"><%= petfound.type_pet %></span>
                    </p>

                    <!-- Botón Ver Detalles estilo petlost -->
                    <div class="mt-auto">
                      <%= link_to petfound_path(petfound), class: 'btn btn-success text-white mb-2' do %>
                        <i class="fa-solid fa-paw me-2"></i>
                        Ver
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <p>No hay mascotas encontradas que coincidan con los filtros.</p>
          <% end %>
        </div>

        <!-- Paginación -->
        <div class="d-flex justify-content-center mt-4">
          <%= paginate @petfounds %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/petfounds/new.html.erb
<%= stylesheet_link_tag 'pet/form', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="body-form">
  <div class="signup-container">
    <div class="left-container">
    </div>

    <div class='right-container'>
      <div class="container-title">
        <h1 class=mb-3>Mascota encontrada</h1>
        <h5>Por favor, completa los datos de tu mascota encontrada</h5>
      </div>
      <%= render "form", petfound: @petfound %>
    </div>
  </div>
</div>

app/views/petfounds/user_pets_founds.html.erb
<body style="background: linear-gradient(to bottom, #f7c6c7, #ffffff);">
  <div class="container mt-5">
    <!-- Botones de navegación superior -->
    <div class="d-flex justify-content-between mb-4">
      <div>
        <%= link_to root_path, class: "btn btn-success btn-lg text-white d-flex align-items-center justify-content-center" do %>
          <%= image_tag 'icons8-home.png', alt: 'Volver', width: 32, height: 32, class: 'me-2'  %> Volver
        <% end %>
      </div>
      <div>
        <%= link_to new_petfound_path, class: 'btn btn-success text-white ms-2' do %>
          <i class="fa-solid fa-dog me-2"></i>
          Perdi mi mascota
        <% end %>
      </div>
    </div>

    <div class="row">
      <!-- Columna para el filtro -->
      <div class="col-md-3">
        <div class="card" style="max-height: 400px; overflow-y: auto;">
          <div class="card-header">
            Filtro por búsqueda
          </div>
          <div class="card-body">
            <%= form_with url: petfounds_path, method: :get, local: true do %>
              <div class="form-group mb-2">
                <%= label_tag :raza, "Raza" %>
                <%= text_field_tag :raza, params[:raza], class: 'form-control' %>
              </div>

              <div class="form-group mb-2">
                <%= label_tag :color, "Color" %>
                <%= text_field_tag :color, params[:color], class: 'form-control' %>
              </div>

              <div class="form-group mb-2">
                <%= label_tag :señas, "Señas particulares" %>
                <%= text_field_tag :signs, params[:signs], class: 'form-control' %>
              </div>

              <div class="form-group mb-2">
                <%= label_tag :fecha_encontrado, "Fecha encontrado" %>
                <%= date_field_tag :day_found, params[:day_found], class: 'form-control' %>
              </div>

              <%= button_tag(type: 'submit', class: 'btn btn-success btn-block text-white') do %>
                <i class="fa-solid fa-filter me-2"></i>
                Filtrar
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

      <!-- Columna para las tarjetas -->
      <div class="col-md-9">
        <div class="row g-3">
          <% if @petfounds.any? %>
            <% @petfounds.each do |petfound| %>
              <div class="col-md-4">
                <div class="card mb-4 shadow-sm d-flex flex-column">
                  <!-- Carrusel de fotos -->
                  <% if petfound.photos.any? %>
                    <div id="carouselPetfound<%= petfound.id %>" class="carousel slide" data-bs-ride="carousel">
                      <div class="carousel-inner">
                        <% petfound.photos.each_with_index do |photo, index| %>
                          <div class="carousel-item <%= 'active' if index == 0 %>">
                            <%= cl_image_tag photo.key, class: 'd-block w-100', style: 'height: 200px; object-fit: cover;', alt: petfound.details %>
                          </div>
                        <% end %>
                      </div>
                      <!-- Controles del carrusel -->
                      <button class="carousel-control-prev" type="button" data-bs-target="#carouselPetfound<%= petfound.id %>" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Anterior</span>
                      </button>
                      <button class="carousel-control-next" type="button" data-bs-target="#carouselPetfound<%= petfound.id %>" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Siguiente</span>
                      </button>
                    </div>
                  <% else %>
                    <!-- Si no hay fotos, muestra una imagen predeterminada -->
                    <%= image_tag 'default-image.png', class: 'card-img-top', style: 'height: 200px; object-fit: cover;', alt: 'No image available' %>
                  <% end %>

                  <div class="card-body d-flex flex-column">
                    <h5 class="card-title mb-2"><%= petfound.details %></h5>

                    <p class="card-text mb-1">
                      <span class="fw-bold" style="color: #00629D;">Raza:</span>
                      <span class="fw-normal text-dark"><%= petfound.breed %></span>
                    </p>

                    <% if petfound.color.present? %>
                      <% colors_array = JSON.parse(petfound.color).reject(&:blank?) %>
                      <p class="card-text mb-1">
                        <span class="fw-bold" style="color: #00629D;">Color:</span>
                        <span class="fw-normal text-dark"><%= colors_array.join(", ") %></span>
                      </p>
                    <% end %>

                    <p class="card-text mb-1">
                      <span class="fw-bold" style="color: #00629D;">Señas particulares:</span>
                      <span class="fw-normal text-dark"><%= petfound.signs %></span>
                    </p>

                    <p class="card-text mb-1">
                      <span class="fw-bold" style="color: #00629D;">Encontrado el:</span>
                      <span class="fw-normal text-dark"><%= petfound.day_found %></span>
                    </p>

                    <p class="card-text mb-1">
                      <span class="fw-bold" style="color: #00629D;">Dirección donde fue encontrado:</span>
                      <span class="fw-normal text-dark"><%= petfound.address %></span>
                    </p>

                    <!-- Botón Ver Detalles estilo petlost -->
                    <div class="mt-auto">
                      <%= link_to petfound_path(petfound), class: 'btn btn-success text-white mb-2' do %>
                        <i class="fa-solid fa-plus"></i>
                        <i class="fa-solid fa-paw me-2"></i>
                        Ver
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <p>No hay mascotas encontradas que coincidan con los filtros.</p>
          <% end %>
        </div>

        <!-- Paginación -->
        <div class="d-flex justify-content-center mt-4">
          <%= paginate @petfounds %>
        </div>
      </div>
    </div>
  </div>
</body>